backup-type: all
backup-destination: ftp

backup-dir-type: relative
backup-dir: backups

ftp-host: sdk.local.spencercolton.tech
ftp-user: pavilion99
ftp-pass: Spencer3899$
ftp-backup-dir: backups

http-user: pavilion99
http-pass: Spencer3899$